name: Install via pip!

on:
  push:
    paths:
      - 'setup.py'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        mkdir pypitmp
        cp {setup.py,requirements.txt} pypitmp
        cp README.md pypitmp/README.rst
        mkdir pypitmp/threp
        cp {__init__.py,api.py,common.py,decode.py,static.py,type.py,utils.py} pypitmp/threp
        cd pypitmp
        python setup.py sdist bdist_wheel
        twine upload dist/*